{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Исключения try-except\n",
    "Исключения (exceptions) - ещё один тип данных в python. Исключения необходимы для того, чтобы сообщать программисту об ошибках."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-1-344b56f1e442>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[1;31m# Пример исключения\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 2\u001b[1;33m \u001b[1;36m100\u001b[0m\u001b[1;33m/\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "# Пример исключения\n",
    "100/0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n"
     ]
    }
   ],
   "source": [
    "# Пример обработки исключения\n",
    "# В блоке try мы выполняем инструкцию, которая может породить исключение, а в блоке except мы перехватываем их.\n",
    "try:\n",
    "    k = 1 / 0\n",
    "except:\n",
    "    k = 0\n",
    "print(k)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Try** - блок кода, где может быть ошибка\n",
    "\n",
    "**Except** - блок кода, когда нужно обработать ошибку\n",
    "\n",
    "**Else** - блок кода, который выполниться, если не было ошибок\n",
    "\n",
    "**Finally** - блок кода, который выполнится всегда вконце"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Введите число123\n",
      "Всё хорошо.\n",
      "Заканчиваем\n"
     ]
    }
   ],
   "source": [
    "i = input('Введите число')\n",
    "try:\n",
    "    int(i)\n",
    "except Exception:\n",
    "    print('Это не число. Выходим.')\n",
    "else:\n",
    "    print('Всё хорошо.')\n",
    "finally:\n",
    "    print('Заканчиваем')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Виды исключений\n",
    "-   **Exception** – то, на чем фактически строятся все остальные ошибки;\n",
    "\n",
    "-   **AttributeError** – возникает, когда ссылка атрибута или присвоение не\n",
    "    могут быть выполнены;\n",
    "\n",
    "-   **IOError** – возникает в том случае, когда операция I/O (такая как оператор\n",
    "    вывода, встроенная функция **open**() или метод объекта-файла) не может быть\n",
    "    выполнена, по связанной с I/O причине: «файл не найден», или «диск\n",
    "    заполнен», иными словами.\n",
    "\n",
    "-   **ImportError** – возникает, когда оператор **import** не может найти\n",
    "    определение модуля, или когда оператор не может найти имя файла, который\n",
    "    должен быть импортирован;\n",
    "\n",
    "-   **IndexError** – возникает, когда индекс последовательности находится вне\n",
    "    допустимого диапазона;\n",
    "\n",
    "-   **KeyError** – возникает, когда ключ сопоставления (dictionary key) не\n",
    "    найден в наборе существующих ключей;\n",
    "\n",
    "-   **KeyboardInterrupt** – возникает, когда пользователь нажимает клавишу\n",
    "    прерывания(обычно Delete или Ctrl+C);\n",
    "\n",
    "-   **NameError** – возникает, когда локальное или глобальное имя не найдено;\n",
    "\n",
    "-   **OSError** – возникает, когда функция получает связанную с системой ошибку;\n",
    "\n",
    "-   **SyntaxError** — возникает, когда синтаксическая ошибка встречается\n",
    "    синтаксическим анализатором;\n",
    "\n",
    "-   **TypeError** – возникает, когда операция или функция применяется к объекту\n",
    "    несоответствующего типа. Связанное значение представляет собой строку, в\n",
    "    которой приводятся подробные сведения о несоответствии типов;\n",
    "\n",
    "-   **ValueError** – возникает, когда встроенная операция или функция получают\n",
    "    аргумент, тип которого правильный, но неправильно значение, и ситуация не\n",
    "    может описано более точно, как при возникновении **IndexError**;\n",
    "\n",
    "-   **ZeroDivisionError** – возникает, когда второй аргумент операции division\n",
    "    или modulo равен нулю;\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
